name: docx_template
description: A Docx template engine.
version: 0.4.0
homepage: https://github.com/PavelS0/docx_template_dart
environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  archive: ^3.6.1
  xml: ^6.5.0
  collection: ^1.18.0
  path: ^1.9.0
dev_dependencies:
  flutter_lints: ^5.0.0
  test: ^1.25.8
